"""
Add new lesson ideas for OSINT, Threat Hunting, Cloud, System, and Blue Team domains
"""

import csv

new_lessons = [
    # OSINT Advanced Topics (order_index 11-20)
    {'lesson_number': 42, 'order_index': 11, 'domain': 'osint', 'difficulty': 2, 'title': 'Dark Web Monitoring and Intelligence Gathering', 'module': 'Module 2: Advanced OSINT', 'topics': 'Tor network, dark web marketplaces, onion link discovery, dark web monitoring tools (Hunchly, OnionScan), credential leak databases, operational security for dark web research', 'prerequisites': '[1,2,3,4,5,6,7,8,9,10]', 'status': 'not_started', 'course_tag': '', 'notes': 'Requires OSINT fundamentals'},
    {'lesson_number': 43, 'order_index': 12, 'domain': 'osint', 'difficulty': 3, 'title': 'Cryptocurrency Tracking and Blockchain Intelligence', 'module': 'Module 2: Advanced OSINT', 'topics': 'Bitcoin, Ethereum blockchain analysis, wallet clustering, transaction graph analysis, tools (Chainalysis, Elliptic, Crystal Blockchain), mixer and tumbler detection, NFT tracking', 'prerequisites': '[42]', 'status': 'not_started', 'course_tag': '', 'notes': ''},
    {'lesson_number': 44, 'order_index': 13, 'domain': 'osint', 'difficulty': 2, 'title': 'Satellite Imagery and Geospatial Intelligence', 'module': 'Module 2: Advanced OSINT', 'topics': 'Google Earth Pro, Sentinel Hub, Planet Labs, historical imagery analysis, geolocation verification, change detection, open source satellite data, military and infrastructure analysis', 'prerequisites': '[7]', 'status': 'not_started', 'course_tag': '', 'notes': 'Builds on geolocation lesson'},
    {'lesson_number': 45, 'order_index': 14, 'domain': 'osint', 'difficulty': 3, 'title': 'Advanced Social Engineering for OSINT', 'module': 'Module 2: Advanced OSINT', 'topics': 'Pretexting, elicitation techniques, social engineering in OSINT context, LinkedIn intelligence gathering, business intelligence, corporate structure mapping, vishing and phishing for intelligence (ethical considerations)', 'prerequisites': '[3]', 'status': 'not_started', 'course_tag': '', 'notes': 'Ethical boundaries emphasized'},
    {'lesson_number': 46, 'order_index': 15, 'domain': 'osint', 'difficulty': 3, 'title': 'OSINT Automation and API Integration', 'module': 'Module 2: Advanced OSINT', 'topics': 'Python for OSINT automation, API integration (Twitter API, Shodan API, VirusTotal API), web scraping with BeautifulSoup and Scrapy, OSINT Framework automation, building custom OSINT tools', 'prerequisites': '[10]', 'status': 'not_started', 'course_tag': '', 'notes': 'Programming skills required'},

    # Threat Hunting Advanced (order_index 11-20)
    {'lesson_number': 47, 'order_index': 11, 'domain': 'threat_hunting', 'difficulty': 2, 'title': 'Hypothesis-Driven Threat Hunting', 'module': 'Module 2: Advanced Hunting', 'topics': 'Hunt hypothesis development, threat modeling for hunters, ATT&CK-based hypothesis creation, hypothesis testing and validation, documenting hunt results', 'prerequisites': '[1,2]', 'status': 'not_started', 'course_tag': '', 'notes': 'Core hunting methodology'},
    {'lesson_number': 48, 'order_index': 12, 'domain': 'threat_hunting', 'difficulty': 3, 'title': 'Advanced EDR Hunting Queries', 'module': 'Module 2: Advanced Hunting', 'topics': 'CrowdStrike Falcon query language, Carbon Black queries, SentinelOne hunting, Microsoft Defender Advanced Hunting (KQL), custom detection rule creation', 'prerequisites': '[6,11]', 'status': 'not_started', 'course_tag': '', 'notes': 'EDR platform specific'},
    {'lesson_number': 49, 'order_index': 13, 'domain': 'threat_hunting', 'difficulty': 3, 'title': 'Behavioral Analytics and Anomaly Detection', 'module': 'Module 2: Advanced Hunting', 'topics': 'User and entity behavior analytics (UEBA), baseline establishment, statistical anomaly detection, machine learning for threat detection, behavioral profiling', 'prerequisites': '[7,9]', 'status': 'not_started', 'course_tag': '', 'notes': 'Analytics focused'},
    {'lesson_number': 50, 'order_index': 14, 'domain': 'threat_hunting', 'difficulty': 3, 'title': 'Threat Hunting Automation and Orchestration', 'module': 'Module 2: Advanced Hunting', 'topics': 'SOAR platforms for hunting, automated hunt playbooks, Python for hunt automation, continuous hunting vs triggered hunts, hunt metrics and measurement', 'prerequisites': '[11,47]', 'status': 'not_started', 'course_tag': '', 'notes': 'Automation emphasis'},
    {'lesson_number': 51, 'order_index': 15, 'domain': 'threat_hunting', 'difficulty': 3, 'title': 'Building and Operating a Threat Hunt Team', 'module': 'Module 2: Advanced Hunting', 'topics': 'Hunt team structure and roles, hunt mission planning, hunt operations tempo, collaboration with SOC and IR, hunt team metrics and KPIs, continuous improvement', 'prerequisites': '[10]', 'status': 'not_started', 'course_tag': '', 'notes': 'Team operations focus'},

    # Cloud Security Deep Dives (order_index 16-30)
    {'lesson_number': 52, 'order_index': 16, 'domain': 'cloud', 'difficulty': 2, 'title': 'AWS Security Services: GuardDuty and Security Hub', 'module': 'Module 2: AWS Security', 'topics': 'GuardDuty threat detection, Security Hub centralized findings, AWS Config compliance, integration with SIEM, automated remediation, threat intelligence feeds', 'prerequisites': '[1]', 'status': 'not_started', 'course_tag': '', 'notes': 'AWS native security'},
    {'lesson_number': 53, 'order_index': 17, 'domain': 'cloud', 'difficulty': 2, 'title': 'AWS Macie and Data Loss Prevention', 'module': 'Module 2: AWS Security', 'topics': 'Macie for sensitive data discovery, S3 bucket scanning, PII and PHI detection, data classification, DLP policies, compliance monitoring', 'prerequisites': '[1,8]', 'status': 'not_started', 'course_tag': '', 'notes': 'Data protection focus'},
    {'lesson_number': 54, 'order_index': 18, 'domain': 'cloud', 'difficulty': 2, 'title': 'Azure Sentinel and Security Operations', 'module': 'Module 3: Azure Security', 'topics': 'Azure Sentinel SIEM, KQL queries for hunting, workbooks and analytics rules, playbooks and automation, integration with Microsoft 365 Defender', 'prerequisites': '[2]', 'status': 'not_started', 'course_tag': '', 'notes': 'Azure cloud SIEM'},
    {'lesson_number': 55, 'order_index': 19, 'domain': 'cloud', 'difficulty': 2, 'title': 'Microsoft Defender for Cloud', 'module': 'Module 3: Azure Security', 'topics': 'Defender for Cloud (formerly Security Center), security posture management, regulatory compliance, workload protection, JIT VM access, adaptive application controls', 'prerequisites': '[2,54]', 'status': 'not_started', 'course_tag': '', 'notes': 'Azure security platform'},
    {'lesson_number': 56, 'order_index': 20, 'domain': 'cloud', 'difficulty': 2, 'title': 'GCP Security Command Center', 'module': 'Module 4: GCP Security', 'topics': 'Security Command Center overview, asset inventory and discovery, vulnerability scanning, threat detection, security findings and recommendations, integration with Chronicle', 'prerequisites': '[]', 'status': 'not_started', 'course_tag': '', 'notes': 'GCP security platform'},
    {'lesson_number': 57, 'order_index': 21, 'domain': 'cloud', 'difficulty': 3, 'title': 'Multi-Cloud Security Architecture', 'module': 'Module 5: Multi-Cloud', 'topics': 'Multi-cloud vs hybrid cloud, centralized security management, cross-cloud identity and access, unified logging and monitoring, cost and complexity considerations', 'prerequisites': '[1,2]', 'status': 'not_started', 'course_tag': '', 'notes': 'Architecture patterns'},
    {'lesson_number': 58, 'order_index': 22, 'domain': 'cloud', 'difficulty': 3, 'title': 'Cloud Incident Response and Forensics', 'module': 'Module 5: Multi-Cloud', 'topics': 'Cloud IR preparation, evidence collection in cloud environments, snapshot and log preservation, cloud forensics tools, coordinating with cloud providers, legal considerations', 'prerequisites': '[1,2,5]', 'status': 'not_started', 'course_tag': '', 'notes': 'IR in cloud context'},

    # System Internals Expansion (order_index 16-30)
    {'lesson_number': 59, 'order_index': 16, 'domain': 'system', 'difficulty': 3, 'title': 'Advanced Windows Kernel Architecture', 'module': 'Module 2: Windows Deep Dive', 'topics': 'Kernel vs user mode, system calls and interrupts, kernel objects and handles, executive subsystems, device drivers and I/O manager, kernel debugging with WinDbg', 'prerequisites': '[1]', 'status': 'not_started', 'course_tag': '', 'notes': 'Advanced kernel concepts'},
    {'lesson_number': 60, 'order_index': 17, 'domain': 'system', 'difficulty': 2, 'title': 'macOS Architecture and Security Model', 'module': 'Module 3: macOS Internals', 'topics': 'XNU kernel (Mach + BSD), macOS security features (SIP, Gatekeeper, XProtect), file system (APFS), process management, macOS logging (unified log), application sandboxing', 'prerequisites': '[4]', 'status': 'not_started', 'course_tag': '', 'notes': 'macOS fundamentals'},
    {'lesson_number': 61, 'order_index': 18, 'domain': 'system', 'difficulty': 3, 'title': 'macOS Security and Endpoint Protection', 'module': 'Module 3: macOS Internals', 'topics': 'Endpoint security framework, TCC (Transparency Consent and Control), code signing and notarization, macOS malware landscape, detection and response on macOS', 'prerequisites': '[60]', 'status': 'not_started', 'course_tag': '', 'notes': 'macOS security focus'},
    {'lesson_number': 62, 'order_index': 19, 'domain': 'system', 'difficulty': 3, 'title': 'Container Runtime Internals', 'module': 'Module 4: Containers', 'topics': 'Docker architecture, container namespaces and cgroups, container networking, storage drivers and volumes, containerd and runc, OCI specifications', 'prerequisites': '[]', 'status': 'not_started', 'course_tag': '', 'notes': 'Container deep dive'},
    {'lesson_number': 63, 'order_index': 20, 'domain': 'system', 'difficulty': 3, 'title': 'Container Security and Isolation', 'module': 'Module 4: Containers', 'topics': 'Container escape techniques, seccomp and AppArmor profiles, capability management, rootless containers, image scanning and vulnerability management, runtime security', 'prerequisites': '[62]', 'status': 'not_started', 'course_tag': '', 'notes': 'Security implications'},
    {'lesson_number': 64, 'order_index': 21, 'domain': 'system', 'difficulty': 3, 'title': 'Hypervisor Architecture and Security', 'module': 'Module 5: Virtualization', 'topics': 'Type 1 vs Type 2 hypervisors, VMware ESXi architecture, Hyper-V architecture, KVM/QEMU, VM escape vulnerabilities, hypervisor hardening', 'prerequisites': '[]', 'status': 'not_started', 'course_tag': '', 'notes': 'Virtualization security'},
    {'lesson_number': 65, 'order_index': 22, 'domain': 'system', 'difficulty': 3, 'title': 'Firmware Security and UEFI', 'module': 'Module 6: Low-Level Security', 'topics': 'UEFI vs legacy BIOS, Secure Boot, UEFI rootkits and bootkits, firmware analysis tools, Intel Boot Guard, measured boot and TPM', 'prerequisites': '[]', 'status': 'not_started', 'course_tag': '', 'notes': 'Firmware level security'},

    # Blue Team Operations (order_index 17-30)
    {'lesson_number': 66, 'order_index': 17, 'domain': 'blue_team', 'difficulty': 2, 'title': 'SOC Operations and Workflows', 'module': 'Module 2: SOC Operations', 'topics': 'SOC organizational structure, shift operations, escalation procedures, SOC metrics and KPIs, tool stack management, SOC maturity models', 'prerequisites': '[1,2]', 'status': 'not_started', 'course_tag': '', 'notes': 'Operational focus'},
    {'lesson_number': 67, 'order_index': 18, 'domain': 'blue_team', 'difficulty': 2, 'title': 'Alert Triage and Investigation', 'module': 'Module 2: SOC Operations', 'topics': 'Alert prioritization, true positive vs false positive determination, investigation frameworks, evidence gathering, documentation standards, escalation criteria', 'prerequisites': '[66]', 'status': 'not_started', 'course_tag': '', 'notes': 'Core SOC skill'},
    {'lesson_number': 68, 'order_index': 19, 'domain': 'blue_team', 'difficulty': 2, 'title': 'Security Playbook Development', 'module': 'Module 2: SOC Operations', 'topics': 'Playbook design principles, runbook vs playbook, SOAR playbook creation, playbook testing and validation, playbook versioning and maintenance', 'prerequisites': '[67,9]', 'status': 'not_started', 'course_tag': '', 'notes': 'Playbook engineering'},
    {'lesson_number': 69, 'order_index': 20, 'domain': 'blue_team', 'difficulty': 3, 'title': 'Security Automation and Orchestration', 'module': 'Module 2: SOC Operations', 'topics': 'SOAR platforms (Cortex XSOAR, Splunk SOAR, Swimlane), API integration, automated response actions, decision trees and logic flows, measuring automation effectiveness', 'prerequisites': '[68]', 'status': 'not_started', 'course_tag': '', 'notes': 'Automation focus'},
    {'lesson_number': 70, 'order_index': 21, 'domain': 'blue_team', 'difficulty': 3, 'title': 'Purple Team Exercises and Collaboration', 'module': 'Module 3: Purple Teaming', 'topics': 'Purple team concepts, adversary emulation for detection testing, red and blue team collaboration, detection gap analysis, continuous validation, purple team metrics', 'prerequisites': '[8]', 'status': 'not_started', 'course_tag': '', 'notes': 'Cross-team collaboration'},
]

# Append to existing CSV
with open('lesson_ideas.csv', 'a', encoding='utf-8', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=['lesson_number', 'order_index', 'domain', 'difficulty', 'title', 'module', 'topics', 'prerequisites', 'status', 'course_tag', 'notes'])
    for lesson in new_lessons:
        writer.writerow(lesson)

print(f'[OK] Added {len(new_lessons)} new lesson ideas to lesson_ideas.csv')
print()
print('Summary by domain:')
domain_counts = {}
for lesson in new_lessons:
    domain = lesson['domain']
    domain_counts[domain] = domain_counts.get(domain, 0) + 1

for domain, count in sorted(domain_counts.items()):
    print(f'  {domain}: {count} lessons added')

print()
print('New lesson ranges:')
print('  OSINT: order_index 11-15 (5 lessons)')
print('  Threat Hunting: order_index 11-15 (5 lessons)')
print('  Cloud: order_index 16-22 (7 lessons)')
print('  System: order_index 16-22 (7 lessons)')
print('  Blue Team: order_index 17-21 (5 lessons)')
